/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Address {
  
  @SerializedName("streetNmbr")
  private Integer streetNmbr = null;
  @SerializedName("addressLine")
  private String addressLine = null;
  @SerializedName("cityName")
  private String cityName = null;
  @SerializedName("postalCode")
  private String postalCode = null;
  @SerializedName("stateProv")
  private String stateProv = null;
  @SerializedName("countryName")
  private String countryName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStreetNmbr() {
    return streetNmbr;
  }
  public void setStreetNmbr(Integer streetNmbr) {
    this.streetNmbr = streetNmbr;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddressLine() {
    return addressLine;
  }
  public void setAddressLine(String addressLine) {
    this.addressLine = addressLine;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStateProv() {
    return stateProv;
  }
  public void setStateProv(String stateProv) {
    this.stateProv = stateProv;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryName() {
    return countryName;
  }
  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return (this.streetNmbr == null ? address.streetNmbr == null : this.streetNmbr.equals(address.streetNmbr)) &&
        (this.addressLine == null ? address.addressLine == null : this.addressLine.equals(address.addressLine)) &&
        (this.cityName == null ? address.cityName == null : this.cityName.equals(address.cityName)) &&
        (this.postalCode == null ? address.postalCode == null : this.postalCode.equals(address.postalCode)) &&
        (this.stateProv == null ? address.stateProv == null : this.stateProv.equals(address.stateProv)) &&
        (this.countryName == null ? address.countryName == null : this.countryName.equals(address.countryName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.streetNmbr == null ? 0: this.streetNmbr.hashCode());
    result = 31 * result + (this.addressLine == null ? 0: this.addressLine.hashCode());
    result = 31 * result + (this.cityName == null ? 0: this.cityName.hashCode());
    result = 31 * result + (this.postalCode == null ? 0: this.postalCode.hashCode());
    result = 31 * result + (this.stateProv == null ? 0: this.stateProv.hashCode());
    result = 31 * result + (this.countryName == null ? 0: this.countryName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("  streetNmbr: ").append(streetNmbr).append("\n");
    sb.append("  addressLine: ").append(addressLine).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  postalCode: ").append(postalCode).append("\n");
    sb.append("  stateProv: ").append(stateProv).append("\n");
    sb.append("  countryName: ").append(countryName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
