/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AvailabilityResult {
  
  @SerializedName("rateplanId")
  private String rateplanId = null;
  @SerializedName("totalPrice")
  private Float totalPrice = null;
  @SerializedName("discount")
  private Float discount = null;
  @SerializedName("currency")
  private String currency = null;
  @SerializedName("isBar")
  private Boolean isBar = null;
  @SerializedName("availability")
  private Integer availability = null;
  @SerializedName("limitedOffer")
  private Boolean limitedOffer = null;
  @SerializedName("popularity")
  private Integer popularity = null;

  /**
   * ID of the rate plan
   **/
  @ApiModelProperty(value = "ID of the rate plan")
  public String getRateplanId() {
    return rateplanId;
  }
  public void setRateplanId(String rateplanId) {
    this.rateplanId = rateplanId;
  }

  /**
   * Total price for the stay
   **/
  @ApiModelProperty(value = "Total price for the stay")
  public Float getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Discount amount offered on this product
   **/
  @ApiModelProperty(value = "Discount amount offered on this product")
  public Float getDiscount() {
    return discount;
  }
  public void setDiscount(Float discount) {
    this.discount = discount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   * Whether this product is the Best Available Rate or not
   **/
  @ApiModelProperty(value = "Whether this product is the Best Available Rate or not")
  public Boolean getIsBar() {
    return isBar;
  }
  public void setIsBar(Boolean isBar) {
    this.isBar = isBar;
  }

  /**
   * Number of rooms that are available through this rate
   **/
  @ApiModelProperty(value = "Number of rooms that are available through this rate")
  public Integer getAvailability() {
    return availability;
  }
  public void setAvailability(Integer availability) {
    this.availability = availability;
  }

  /**
   * Whether this product is a limited offer or not
   **/
  @ApiModelProperty(value = "Whether this product is a limited offer or not")
  public Boolean getLimitedOffer() {
    return limitedOffer;
  }
  public void setLimitedOffer(Boolean limitedOffer) {
    this.limitedOffer = limitedOffer;
  }

  /**
   * The popularity of the current product compared to the others
   * minimum: 0
   * maximum: 100
   **/
  @ApiModelProperty(value = "The popularity of the current product compared to the others")
  public Integer getPopularity() {
    return popularity;
  }
  public void setPopularity(Integer popularity) {
    this.popularity = popularity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailabilityResult availabilityResult = (AvailabilityResult) o;
    return (this.rateplanId == null ? availabilityResult.rateplanId == null : this.rateplanId.equals(availabilityResult.rateplanId)) &&
        (this.totalPrice == null ? availabilityResult.totalPrice == null : this.totalPrice.equals(availabilityResult.totalPrice)) &&
        (this.discount == null ? availabilityResult.discount == null : this.discount.equals(availabilityResult.discount)) &&
        (this.currency == null ? availabilityResult.currency == null : this.currency.equals(availabilityResult.currency)) &&
        (this.isBar == null ? availabilityResult.isBar == null : this.isBar.equals(availabilityResult.isBar)) &&
        (this.availability == null ? availabilityResult.availability == null : this.availability.equals(availabilityResult.availability)) &&
        (this.limitedOffer == null ? availabilityResult.limitedOffer == null : this.limitedOffer.equals(availabilityResult.limitedOffer)) &&
        (this.popularity == null ? availabilityResult.popularity == null : this.popularity.equals(availabilityResult.popularity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.rateplanId == null ? 0: this.rateplanId.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.discount == null ? 0: this.discount.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.isBar == null ? 0: this.isBar.hashCode());
    result = 31 * result + (this.availability == null ? 0: this.availability.hashCode());
    result = 31 * result + (this.limitedOffer == null ? 0: this.limitedOffer.hashCode());
    result = 31 * result + (this.popularity == null ? 0: this.popularity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailabilityResult {\n");
    
    sb.append("  rateplanId: ").append(rateplanId).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  discount: ").append(discount).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  isBar: ").append(isBar).append("\n");
    sb.append("  availability: ").append(availability).append("\n");
    sb.append("  limitedOffer: ").append(limitedOffer).append("\n");
    sb.append("  popularity: ").append(popularity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
