/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BasicService {
  
  @SerializedName("serviceId")
  private String serviceId = null;
  @SerializedName("price")
  private Float price = null;
  @SerializedName("discount")
  private Float discount = null;
  /**
   * The pricing type of the service
   */
  public enum PricingTypeEnum {
    STAY("Per stay"),

    PERSON("Per person"),

    NIGHT("Per night"),

    PERSON_PER_NIGHT("Per person per night"),

    USE("Per use");

    private String value;

    PricingTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }


    public static PricingTypeEnum fromValue(String text) {
      for (PricingTypeEnum b : PricingTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @SerializedName("pricingType")
  private PricingTypeEnum pricingType = null;
  @SerializedName("totalPrice")
  private Float totalPrice = null;
  @SerializedName("totalDiscount")
  private Float totalDiscount = null;
  @SerializedName("currency")
  private CurrencyCode currency = null;
  @SerializedName("included")
  private Boolean included = null;

  /**
   * ID of the service
   **/
  @ApiModelProperty(value = "ID of the service")
  public String getServiceId() {
    return serviceId;
  }
  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  /**
   * Price of the service
   **/
  @ApiModelProperty(value = "Price of the service")
  public Float getPrice() {
    return price;
  }
  public void setPrice(Float price) {
    this.price = price;
  }

  /**
   * Discount amount offered on this service
   **/
  @ApiModelProperty(value = "Discount amount offered on this service")
  public Float getDiscount() {
    return discount;
  }
  public void setDiscount(Float discount) {
    this.discount = discount;
  }

  /**
   * The pricing type of the service
   **/
  @ApiModelProperty(value = "The pricing type of the service")
  public PricingTypeEnum getPricingType() {
    return pricingType;
  }
  public void setPricingType(PricingTypeEnum pricingType) {
    this.pricingType = pricingType;
  }

  /**
   * Total price for the service
   **/
  @ApiModelProperty(value = "Total price for the service")
  public Float getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Total discount amount offered on this service
   **/
  @ApiModelProperty(value = "Total discount amount offered on this service")
  public Float getTotalDiscount() {
    return totalDiscount;
  }
  public void setTotalDiscount(Float totalDiscount) {
    this.totalDiscount = totalDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CurrencyCode getCurrency() {
    return currency;
  }
  public void setCurrency(CurrencyCode currency) {
    this.currency = currency;
  }

  /**
   * Whether the service price is included in the roomstay price or not
   **/
  @ApiModelProperty(value = "Whether the service price is included in the roomstay price or not")
  public Boolean getIncluded() {
    return included;
  }
  public void setIncluded(Boolean included) {
    this.included = included;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicService basicService = (BasicService) o;
    return (this.serviceId == null ? basicService.serviceId == null : this.serviceId.equals(basicService.serviceId)) &&
        (this.price == null ? basicService.price == null : this.price.equals(basicService.price)) &&
        (this.discount == null ? basicService.discount == null : this.discount.equals(basicService.discount)) &&
        (this.pricingType == null ? basicService.pricingType == null : this.pricingType.equals(basicService.pricingType)) &&
        (this.totalPrice == null ? basicService.totalPrice == null : this.totalPrice.equals(basicService.totalPrice)) &&
        (this.totalDiscount == null ? basicService.totalDiscount == null : this.totalDiscount.equals(basicService.totalDiscount)) &&
        (this.currency == null ? basicService.currency == null : this.currency.equals(basicService.currency)) &&
        (this.included == null ? basicService.included == null : this.included.equals(basicService.included));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.serviceId == null ? 0: this.serviceId.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.discount == null ? 0: this.discount.hashCode());
    result = 31 * result + (this.pricingType == null ? 0: this.pricingType.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.totalDiscount == null ? 0: this.totalDiscount.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.included == null ? 0: this.included.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicService {\n");
    
    sb.append("  serviceId: ").append(serviceId).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  discount: ").append(discount).append("\n");
    sb.append("  pricingType: ").append(pricingType).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  totalDiscount: ").append(totalDiscount).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  included: ").append(included).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
