/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

@ApiModel(description = "")
public class CancelReservationRequest implements Serializable {
  private static final long serialVersionUID = 112349L;

  @SerializedName("reservationId")
  private String reservationId = null;
  @SerializedName("reservationEmail")
  private String reservationEmail = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReservationId() {
    return reservationId;
  }
  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReservationEmail() {
    return reservationEmail;
  }
  public void setReservationEmail(String reservationEmail) {
    this.reservationEmail = reservationEmail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelReservationRequest cancelReservationRequest = (CancelReservationRequest) o;
    return (this.reservationId == null ? cancelReservationRequest.reservationId == null : this.reservationId.equals(cancelReservationRequest.reservationId)) &&
        (this.reservationEmail == null ? cancelReservationRequest.reservationEmail == null : this.reservationEmail.equals(cancelReservationRequest.reservationEmail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.reservationId == null ? 0: this.reservationId.hashCode());
    result = 31 * result + (this.reservationEmail == null ? 0: this.reservationEmail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelReservationRequest {\n");
    
    sb.append("  reservationId: ").append(reservationId).append("\n");
    sb.append("  reservationEmail: ").append(reservationEmail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
