/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ContactInfo {
  
  @SerializedName("companyName")
  private String companyName = null;
  @SerializedName("addresses")
  private List<Address> addresses = null;
  @SerializedName("phones")
  private List<Phone> phones = null;
  @SerializedName("emails")
  private List<Email> emails = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompanyName() {
    return companyName;
  }
  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Address> getAddresses() {
    return addresses;
  }
  public void setAddresses(List<Address> addresses) {
    this.addresses = addresses;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Phone> getPhones() {
    return phones;
  }
  public void setPhones(List<Phone> phones) {
    this.phones = phones;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Email> getEmails() {
    return emails;
  }
  public void setEmails(List<Email> emails) {
    this.emails = emails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactInfo contactInfo = (ContactInfo) o;
    return (this.companyName == null ? contactInfo.companyName == null : this.companyName.equals(contactInfo.companyName)) &&
        (this.addresses == null ? contactInfo.addresses == null : this.addresses.equals(contactInfo.addresses)) &&
        (this.phones == null ? contactInfo.phones == null : this.phones.equals(contactInfo.phones)) &&
        (this.emails == null ? contactInfo.emails == null : this.emails.equals(contactInfo.emails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.companyName == null ? 0: this.companyName.hashCode());
    result = 31 * result + (this.addresses == null ? 0: this.addresses.hashCode());
    result = 31 * result + (this.phones == null ? 0: this.phones.hashCode());
    result = 31 * result + (this.emails == null ? 0: this.emails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactInfo {\n");
    
    sb.append("  companyName: ").append(companyName).append("\n");
    sb.append("  addresses: ").append(addresses).append("\n");
    sb.append("  phones: ").append(phones).append("\n");
    sb.append("  emails: ").append(emails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
