/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Descriptions {
  
  @SerializedName("multimediadescriptions")
  private List<MultimediaDescription> multimediadescriptions = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MultimediaDescription> getMultimediadescriptions() {
    return multimediadescriptions;
  }
  public void setMultimediadescriptions(List<MultimediaDescription> multimediadescriptions) {
    this.multimediadescriptions = multimediadescriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Descriptions descriptions = (Descriptions) o;
    return (this.multimediadescriptions == null ? descriptions.multimediadescriptions == null : this.multimediadescriptions.equals(descriptions.multimediadescriptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.multimediadescriptions == null ? 0: this.multimediadescriptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Descriptions {\n");
    
    sb.append("  multimediadescriptions: ").append(multimediadescriptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
