/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.io.Serializable;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GuestRoom implements Serializable {
  private static final long serialVersionUID = 112554L;

  @SerializedName("id")
  private String id = null;
  @SerializedName("roomTypeName")
  private String roomTypeName = null;
  @SerializedName("minOccupancy")
  private Integer minOccupancy = null;
  @SerializedName("maxOccupancy")
  private Integer maxOccupancy = null;
  @SerializedName("maxChildOccupancy")
  private Integer maxChildOccupancy = null;
  @SerializedName("maxAdultOccupancy")
  private Integer maxAdultOccupancy = null;
  @SerializedName("typeRoom")
  private TypeRoom typeRoom = null;
  @SerializedName("amenities")
  private List<RoomAmenity> amenities = null;
  @SerializedName("multimediaDescriptions")
  private List<MultimediaDescription> multimediaDescriptions = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRoomTypeName() {
    return roomTypeName;
  }
  public void setRoomTypeName(String roomTypeName) {
    this.roomTypeName = roomTypeName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMinOccupancy() {
    return minOccupancy;
  }
  public void setMinOccupancy(Integer minOccupancy) {
    this.minOccupancy = minOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxOccupancy() {
    return maxOccupancy;
  }
  public void setMaxOccupancy(Integer maxOccupancy) {
    this.maxOccupancy = maxOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxChildOccupancy() {
    return maxChildOccupancy;
  }
  public void setMaxChildOccupancy(Integer maxChildOccupancy) {
    this.maxChildOccupancy = maxChildOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxAdultOccupancy() {
    return maxAdultOccupancy;
  }
  public void setMaxAdultOccupancy(Integer maxAdultOccupancy) {
    this.maxAdultOccupancy = maxAdultOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TypeRoom getTypeRoom() {
    return typeRoom;
  }
  public void setTypeRoom(TypeRoom typeRoom) {
    this.typeRoom = typeRoom;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<RoomAmenity> getAmenities() {
    return amenities;
  }
  public void setAmenities(List<RoomAmenity> amenities) {
    this.amenities = amenities;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MultimediaDescription> getMultimediaDescriptions() {
    return multimediaDescriptions;
  }
  public void setMultimediaDescriptions(List<MultimediaDescription> multimediaDescriptions) {
    this.multimediaDescriptions = multimediaDescriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestRoom guestRoom = (GuestRoom) o;
    return (this.id == null ? guestRoom.id == null : this.id.equals(guestRoom.id)) &&
        (this.roomTypeName == null ? guestRoom.roomTypeName == null : this.roomTypeName.equals(guestRoom.roomTypeName)) &&
        (this.minOccupancy == null ? guestRoom.minOccupancy == null : this.minOccupancy.equals(guestRoom.minOccupancy)) &&
        (this.maxOccupancy == null ? guestRoom.maxOccupancy == null : this.maxOccupancy.equals(guestRoom.maxOccupancy)) &&
        (this.maxChildOccupancy == null ? guestRoom.maxChildOccupancy == null : this.maxChildOccupancy.equals(guestRoom.maxChildOccupancy)) &&
        (this.maxAdultOccupancy == null ? guestRoom.maxAdultOccupancy == null : this.maxAdultOccupancy.equals(guestRoom.maxAdultOccupancy)) &&
        (this.typeRoom == null ? guestRoom.typeRoom == null : this.typeRoom.equals(guestRoom.typeRoom)) &&
        (this.amenities == null ? guestRoom.amenities == null : this.amenities.equals(guestRoom.amenities)) &&
        (this.multimediaDescriptions == null ? guestRoom.multimediaDescriptions == null : this.multimediaDescriptions.equals(guestRoom.multimediaDescriptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.roomTypeName == null ? 0: this.roomTypeName.hashCode());
    result = 31 * result + (this.minOccupancy == null ? 0: this.minOccupancy.hashCode());
    result = 31 * result + (this.maxOccupancy == null ? 0: this.maxOccupancy.hashCode());
    result = 31 * result + (this.maxChildOccupancy == null ? 0: this.maxChildOccupancy.hashCode());
    result = 31 * result + (this.maxAdultOccupancy == null ? 0: this.maxAdultOccupancy.hashCode());
    result = 31 * result + (this.typeRoom == null ? 0: this.typeRoom.hashCode());
    result = 31 * result + (this.amenities == null ? 0: this.amenities.hashCode());
    result = 31 * result + (this.multimediaDescriptions == null ? 0: this.multimediaDescriptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestRoom {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  roomTypeName: ").append(roomTypeName).append("\n");
    sb.append("  minOccupancy: ").append(minOccupancy).append("\n");
    sb.append("  maxOccupancy: ").append(maxOccupancy).append("\n");
    sb.append("  maxChildOccupancy: ").append(maxChildOccupancy).append("\n");
    sb.append("  maxAdultOccupancy: ").append(maxAdultOccupancy).append("\n");
    sb.append("  typeRoom: ").append(typeRoom).append("\n");
    sb.append("  amenities: ").append(amenities).append("\n");
    sb.append("  multimediaDescriptions: ").append(multimediaDescriptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
