/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GuestCount {
  
  @SerializedName("ageQualifyingCode")
  private Integer ageQualifyingCode = null;
  @SerializedName("count")
  private Integer count = null;

  /**
   * A code representing the age category: 10 (Adults), 8 (Children), 7 (Infants)
   **/
  @ApiModelProperty(value = "A code representing the age category: 10 (Adults), 8 (Children), 7 (Infants)")
  public Integer getAgeQualifyingCode() {
    return ageQualifyingCode;
  }
  public void setAgeQualifyingCode(Integer ageQualifyingCode) {
    this.ageQualifyingCode = ageQualifyingCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestCount guestCount = (GuestCount) o;
    return (this.ageQualifyingCode == null ? guestCount.ageQualifyingCode == null : this.ageQualifyingCode.equals(guestCount.ageQualifyingCode)) &&
        (this.count == null ? guestCount.count == null : this.count.equals(guestCount.count));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ageQualifyingCode == null ? 0: this.ageQualifyingCode.hashCode());
    result = 31 * result + (this.count == null ? 0: this.count.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestCount {\n");
    
    sb.append("  ageQualifyingCode: ").append(ageQualifyingCode).append("\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
