/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

@ApiModel(description = "")
public class HotelProductRatePlans implements Serializable {
  private static final long serialVersionUID = 112569L;

  @SerializedName("ratePlanCode")
  private String ratePlanCode = null;
  @SerializedName("ratePlanName")
  private String ratePlanName = null;
  @SerializedName("currencyCode")
  private CurrencyCode currencyCode = null;
  @SerializedName("descriptions")
  private MultiDescription descriptions = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRatePlanCode() {
    return ratePlanCode;
  }
  public void setRatePlanCode(String ratePlanCode) {
    this.ratePlanCode = ratePlanCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRatePlanName() {
    return ratePlanName;
  }
  public void setRatePlanName(String ratePlanName) {
    this.ratePlanName = ratePlanName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CurrencyCode getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(CurrencyCode currencyCode) {
    this.currencyCode = currencyCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MultiDescription getDescriptions() {
    return descriptions;
  }
  public void setDescriptions(MultiDescription descriptions) {
    this.descriptions = descriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelProductRatePlans hotelProductRatePlans = (HotelProductRatePlans) o;
    return (this.ratePlanCode == null ? hotelProductRatePlans.ratePlanCode == null : this.ratePlanCode.equals(hotelProductRatePlans.ratePlanCode)) &&
        (this.ratePlanName == null ? hotelProductRatePlans.ratePlanName == null : this.ratePlanName.equals(hotelProductRatePlans.ratePlanName)) &&
        (this.currencyCode == null ? hotelProductRatePlans.currencyCode == null : this.currencyCode.equals(hotelProductRatePlans.currencyCode)) &&
        (this.descriptions == null ? hotelProductRatePlans.descriptions == null : this.descriptions.equals(hotelProductRatePlans.descriptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ratePlanCode == null ? 0: this.ratePlanCode.hashCode());
    result = 31 * result + (this.ratePlanName == null ? 0: this.ratePlanName.hashCode());
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    result = 31 * result + (this.descriptions == null ? 0: this.descriptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelProductRatePlans {\n");
    
    sb.append("  ratePlanCode: ").append(ratePlanCode).append("\n");
    sb.append("  ratePlanName: ").append(ratePlanName).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  descriptions: ").append(descriptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
