/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.io.Serializable;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelDescriptiveInfo implements Serializable{
  private static final long serialVersionUID = 112557L;

  @SerializedName("hotelId")
  private String hotelId = null;
  @SerializedName("hotelName")
  private String hotelName = null;
  @SerializedName("areaUnitOfMeasureCode")
  private Integer areaUnitOfMeasureCode = null;
  @SerializedName("distanceUnitOfMeasureCode")
  private Integer distanceUnitOfMeasureCode = null;
  @SerializedName("timeZone")
  private String timeZone = null;
  @SerializedName("weightUnitOfMeasureCode")
  private Integer weightUnitOfMeasureCode = null;
  @SerializedName("currencyCode")
  private String currencyCode = null;
  @SerializedName("hotelInfo")
  private HotelInfo hotelInfo = null;
  @SerializedName("affiliationInfo")
  private HotelDescriptiveInfoAffiliationInfo affiliationInfo = null;
  @SerializedName("facilityInfo")
  private HotelDescriptiveInfoFacilityInfo facilityInfo = null;
  @SerializedName("contactInfos")
  private List<ContactInfo> contactInfos = null;
  @SerializedName("policies")
  private HotelDescriptiveInfoPolicies policies = null;

  /**
   * The hotel ID.
   **/
  @ApiModelProperty(value = "The hotel ID.")
  public String getHotelId() {
    return hotelId;
  }
  public void setHotelId(String hotelId) {
    this.hotelId = hotelId;
  }

  /**
   * The hotel name.
   **/
  @ApiModelProperty(value = "The hotel name.")
  public String getHotelName() {
    return hotelName;
  }
  public void setHotelName(String hotelName) {
    this.hotelName = hotelName;
  }

  /**
   * Provides the unit of measure in which area is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).
   **/
  @ApiModelProperty(value = "Provides the unit of measure in which area is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).")
  public Integer getAreaUnitOfMeasureCode() {
    return areaUnitOfMeasureCode;
  }
  public void setAreaUnitOfMeasureCode(Integer areaUnitOfMeasureCode) {
    this.areaUnitOfMeasureCode = areaUnitOfMeasureCode;
  }

  /**
   * Provides the unit of measure in which distance is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).
   **/
  @ApiModelProperty(value = "Provides the unit of measure in which distance is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).")
  public Integer getDistanceUnitOfMeasureCode() {
    return distanceUnitOfMeasureCode;
  }
  public void setDistanceUnitOfMeasureCode(Integer distanceUnitOfMeasureCode) {
    this.distanceUnitOfMeasureCode = distanceUnitOfMeasureCode;
  }

  /**
   * Describes the local time zone in which the hotel is located. This could include additional information regarding time zones (e.g., Daylight Saving Time observed), a proprietary code, the difference between the local time and GMT.
   **/
  @ApiModelProperty(value = "Describes the local time zone in which the hotel is located. This could include additional information regarding time zones (e.g., Daylight Saving Time observed), a proprietary code, the difference between the local time and GMT.")
  public String getTimeZone() {
    return timeZone;
  }
  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  /**
   * Provides the unit of measure in which weight is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).
   **/
  @ApiModelProperty(value = "Provides the unit of measure in which weight is provided in this message. Refer to OpenTravel Code List Unit of Measure (UOM).")
  public Integer getWeightUnitOfMeasureCode() {
    return weightUnitOfMeasureCode;
  }
  public void setWeightUnitOfMeasureCode(Integer weightUnitOfMeasureCode) {
    this.weightUnitOfMeasureCode = weightUnitOfMeasureCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelInfo getHotelInfo() {
    return hotelInfo;
  }
  public void setHotelInfo(HotelInfo hotelInfo) {
    this.hotelInfo = hotelInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelDescriptiveInfoAffiliationInfo getAffiliationInfo() {
    return affiliationInfo;
  }
  public void setAffiliationInfo(HotelDescriptiveInfoAffiliationInfo affiliationInfo) {
    this.affiliationInfo = affiliationInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelDescriptiveInfoFacilityInfo getFacilityInfo() {
    return facilityInfo;
  }
  public void setFacilityInfo(HotelDescriptiveInfoFacilityInfo facilityInfo) {
    this.facilityInfo = facilityInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ContactInfo> getContactInfos() {
    return contactInfos;
  }
  public void setContactInfos(List<ContactInfo> contactInfos) {
    this.contactInfos = contactInfos;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelDescriptiveInfoPolicies getPolicies() {
    return policies;
  }
  public void setPolicies(HotelDescriptiveInfoPolicies policies) {
    this.policies = policies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelDescriptiveInfo hotelDescriptiveInfo = (HotelDescriptiveInfo) o;
    return (this.hotelId == null ? hotelDescriptiveInfo.hotelId == null : this.hotelId.equals(hotelDescriptiveInfo.hotelId)) &&
        (this.hotelName == null ? hotelDescriptiveInfo.hotelName == null : this.hotelName.equals(hotelDescriptiveInfo.hotelName)) &&
        (this.areaUnitOfMeasureCode == null ? hotelDescriptiveInfo.areaUnitOfMeasureCode == null : this.areaUnitOfMeasureCode.equals(hotelDescriptiveInfo.areaUnitOfMeasureCode)) &&
        (this.distanceUnitOfMeasureCode == null ? hotelDescriptiveInfo.distanceUnitOfMeasureCode == null : this.distanceUnitOfMeasureCode.equals(hotelDescriptiveInfo.distanceUnitOfMeasureCode)) &&
        (this.timeZone == null ? hotelDescriptiveInfo.timeZone == null : this.timeZone.equals(hotelDescriptiveInfo.timeZone)) &&
        (this.weightUnitOfMeasureCode == null ? hotelDescriptiveInfo.weightUnitOfMeasureCode == null : this.weightUnitOfMeasureCode.equals(hotelDescriptiveInfo.weightUnitOfMeasureCode)) &&
        (this.currencyCode == null ? hotelDescriptiveInfo.currencyCode == null : this.currencyCode.equals(hotelDescriptiveInfo.currencyCode)) &&
        (this.hotelInfo == null ? hotelDescriptiveInfo.hotelInfo == null : this.hotelInfo.equals(hotelDescriptiveInfo.hotelInfo)) &&
        (this.affiliationInfo == null ? hotelDescriptiveInfo.affiliationInfo == null : this.affiliationInfo.equals(hotelDescriptiveInfo.affiliationInfo)) &&
        (this.facilityInfo == null ? hotelDescriptiveInfo.facilityInfo == null : this.facilityInfo.equals(hotelDescriptiveInfo.facilityInfo)) &&
        (this.contactInfos == null ? hotelDescriptiveInfo.contactInfos == null : this.contactInfos.equals(hotelDescriptiveInfo.contactInfos)) &&
        (this.policies == null ? hotelDescriptiveInfo.policies == null : this.policies.equals(hotelDescriptiveInfo.policies));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.hotelId == null ? 0: this.hotelId.hashCode());
    result = 31 * result + (this.hotelName == null ? 0: this.hotelName.hashCode());
    result = 31 * result + (this.areaUnitOfMeasureCode == null ? 0: this.areaUnitOfMeasureCode.hashCode());
    result = 31 * result + (this.distanceUnitOfMeasureCode == null ? 0: this.distanceUnitOfMeasureCode.hashCode());
    result = 31 * result + (this.timeZone == null ? 0: this.timeZone.hashCode());
    result = 31 * result + (this.weightUnitOfMeasureCode == null ? 0: this.weightUnitOfMeasureCode.hashCode());
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    result = 31 * result + (this.hotelInfo == null ? 0: this.hotelInfo.hashCode());
    result = 31 * result + (this.affiliationInfo == null ? 0: this.affiliationInfo.hashCode());
    result = 31 * result + (this.facilityInfo == null ? 0: this.facilityInfo.hashCode());
    result = 31 * result + (this.contactInfos == null ? 0: this.contactInfos.hashCode());
    result = 31 * result + (this.policies == null ? 0: this.policies.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelDescriptiveInfo {\n");
    
    sb.append("  hotelId: ").append(hotelId).append("\n");
    sb.append("  hotelName: ").append(hotelName).append("\n");
    sb.append("  areaUnitOfMeasureCode: ").append(areaUnitOfMeasureCode).append("\n");
    sb.append("  distanceUnitOfMeasureCode: ").append(distanceUnitOfMeasureCode).append("\n");
    sb.append("  timeZone: ").append(timeZone).append("\n");
    sb.append("  weightUnitOfMeasureCode: ").append(weightUnitOfMeasureCode).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  hotelInfo: ").append(hotelInfo).append("\n");
    sb.append("  affiliationInfo: ").append(affiliationInfo).append("\n");
    sb.append("  facilityInfo: ").append(facilityInfo).append("\n");
    sb.append("  contactInfos: ").append(contactInfos).append("\n");
    sb.append("  policies: ").append(policies).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
