/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.io.Serializable;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Contains descriptive information about a hotel.
 **/
@ApiModel(description = "Contains descriptive information about a hotel.")
public class HotelInfo implements Serializable {
  private static final long serialVersionUID = 112563L;

  @SerializedName("whenBuilt")
  private Date whenBuilt = null;
  @SerializedName("position")
  private HotelInfoPosition position = null;
  @SerializedName("descriptions")
  private Descriptions descriptions = null;
  @SerializedName("services")
  private List<Service> services = null;

  /**
   * The date that the hotel facility was built, usually just the year.
   **/
  @ApiModelProperty(value = "The date that the hotel facility was built, usually just the year.")
  public Date getWhenBuilt() {
    return whenBuilt;
  }
  public void setWhenBuilt(Date whenBuilt) {
    this.whenBuilt = whenBuilt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelInfoPosition getPosition() {
    return position;
  }
  public void setPosition(HotelInfoPosition position) {
    this.position = position;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Descriptions getDescriptions() {
    return descriptions;
  }
  public void setDescriptions(Descriptions descriptions) {
    this.descriptions = descriptions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Service> getServices() {
    return services;
  }
  public void setServices(List<Service> services) {
    this.services = services;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelInfo hotelInfo = (HotelInfo) o;
    return (this.whenBuilt == null ? hotelInfo.whenBuilt == null : this.whenBuilt.equals(hotelInfo.whenBuilt)) &&
        (this.position == null ? hotelInfo.position == null : this.position.equals(hotelInfo.position)) &&
        (this.descriptions == null ? hotelInfo.descriptions == null : this.descriptions.equals(hotelInfo.descriptions)) &&
        (this.services == null ? hotelInfo.services == null : this.services.equals(hotelInfo.services));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.whenBuilt == null ? 0: this.whenBuilt.hashCode());
    result = 31 * result + (this.position == null ? 0: this.position.hashCode());
    result = 31 * result + (this.descriptions == null ? 0: this.descriptions.hashCode());
    result = 31 * result + (this.services == null ? 0: this.services.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelInfo {\n");
    
    sb.append("  whenBuilt: ").append(whenBuilt).append("\n");
    sb.append("  position: ").append(position).append("\n");
    sb.append("  descriptions: ").append(descriptions).append("\n");
    sb.append("  services: ").append(services).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
