/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * General policy information
 **/
@ApiModel(description = "General policy information")
public class HotelDescriptiveInfoPoliciesPolicyInfo {
  
  @SerializedName("minChildAge")
  private Integer minChildAge = null;
  @SerializedName("maxChildAge")
  private Integer maxChildAge = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMinChildAge() {
    return minChildAge;
  }
  public void setMinChildAge(Integer minChildAge) {
    this.minChildAge = minChildAge;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxChildAge() {
    return maxChildAge;
  }
  public void setMaxChildAge(Integer maxChildAge) {
    this.maxChildAge = maxChildAge;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelDescriptiveInfoPoliciesPolicyInfo hotelDescriptiveInfoPoliciesPolicyInfo = (HotelDescriptiveInfoPoliciesPolicyInfo) o;
    return (this.minChildAge == null ? hotelDescriptiveInfoPoliciesPolicyInfo.minChildAge == null : this.minChildAge.equals(hotelDescriptiveInfoPoliciesPolicyInfo.minChildAge)) &&
        (this.maxChildAge == null ? hotelDescriptiveInfoPoliciesPolicyInfo.maxChildAge == null : this.maxChildAge.equals(hotelDescriptiveInfoPoliciesPolicyInfo.maxChildAge));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.minChildAge == null ? 0: this.minChildAge.hashCode());
    result = 31 * result + (this.maxChildAge == null ? 0: this.maxChildAge.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelDescriptiveInfoPoliciesPolicyInfo {\n");
    
    sb.append("  minChildAge: ").append(minChildAge).append("\n");
    sb.append("  maxChildAge: ").append(maxChildAge).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
