/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelProductRoomTypes {
  
  @SerializedName("roomTypeCode")
  private String roomTypeCode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRoomTypeCode() {
    return roomTypeCode;
  }
  public void setRoomTypeCode(String roomTypeCode) {
    this.roomTypeCode = roomTypeCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelProductRoomTypes hotelProductRoomTypes = (HotelProductRoomTypes) o;
    return (this.roomTypeCode == null ? hotelProductRoomTypes.roomTypeCode == null : this.roomTypeCode.equals(hotelProductRoomTypes.roomTypeCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.roomTypeCode == null ? 0: this.roomTypeCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelProductRoomTypes {\n");
    
    sb.append("  roomTypeCode: ").append(roomTypeCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
