/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Provides information pertaining to the hotel facility itself. Describes the facilities provided at the hotel, including meeting rooms and restaurants.
 **/
@ApiModel(description = "Provides information pertaining to the hotel facility itself. Describes the facilities provided at the hotel, including meeting rooms and restaurants.")
public class HotelDescriptiveInfoFacilityInfo {
  
  @SerializedName("guestRooms")
  private List<GuestRoom> guestRooms = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<GuestRoom> getGuestRooms() {
    return guestRooms;
  }
  public void setGuestRooms(List<GuestRoom> guestRooms) {
    this.guestRooms = guestRooms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelDescriptiveInfoFacilityInfo hotelDescriptiveInfoFacilityInfo = (HotelDescriptiveInfoFacilityInfo) o;
    return (this.guestRooms == null ? hotelDescriptiveInfoFacilityInfo.guestRooms == null : this.guestRooms.equals(hotelDescriptiveInfoFacilityInfo.guestRooms));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.guestRooms == null ? 0: this.guestRooms.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelDescriptiveInfoFacilityInfo {\n");
    
    sb.append("  guestRooms: ").append(guestRooms).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
