/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Provides information about the hotel policies (payment, guarantees, etc.)
 **/
@ApiModel(description = "Provides information about the hotel policies (payment, guarantees, etc.)")
public class HotelDescriptiveInfoPolicies {
  
  @SerializedName("policyInfo")
  private HotelDescriptiveInfoPoliciesPolicyInfo policyInfo = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public HotelDescriptiveInfoPoliciesPolicyInfo getPolicyInfo() {
    return policyInfo;
  }
  public void setPolicyInfo(HotelDescriptiveInfoPoliciesPolicyInfo policyInfo) {
    this.policyInfo = policyInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelDescriptiveInfoPolicies hotelDescriptiveInfoPolicies = (HotelDescriptiveInfoPolicies) o;
    return (this.policyInfo == null ? hotelDescriptiveInfoPolicies.policyInfo == null : this.policyInfo.equals(hotelDescriptiveInfoPolicies.policyInfo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.policyInfo == null ? 0: this.policyInfo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelDescriptiveInfoPolicies {\n");
    
    sb.append("  policyInfo: ").append(policyInfo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
