/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelInfoPosition {
  
  @SerializedName("altitude")
  private BigDecimal altitude = null;
  @SerializedName("latitude")
  private BigDecimal latitude = null;
  @SerializedName("longitude")
  private BigDecimal longitude = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getAltitude() {
    return altitude;
  }
  public void setAltitude(BigDecimal altitude) {
    this.altitude = altitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLatitude() {
    return latitude;
  }
  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getLongitude() {
    return longitude;
  }
  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelInfoPosition hotelInfoPosition = (HotelInfoPosition) o;
    return (this.altitude == null ? hotelInfoPosition.altitude == null : this.altitude.equals(hotelInfoPosition.altitude)) &&
        (this.latitude == null ? hotelInfoPosition.latitude == null : this.latitude.equals(hotelInfoPosition.latitude)) &&
        (this.longitude == null ? hotelInfoPosition.longitude == null : this.longitude.equals(hotelInfoPosition.longitude));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.altitude == null ? 0: this.altitude.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelInfoPosition {\n");
    
    sb.append("  altitude: ").append(altitude).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
