/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelProduct {
  
  @SerializedName("ID")
  private String ID = null;
  @SerializedName("roomTypes")
  private List<HotelProductRoomTypes> roomTypes = null;
  @SerializedName("ratePlans")
  private List<HotelProductRatePlans> ratePlans = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }
  public void setID(String ID) {
    this.ID = ID;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<HotelProductRoomTypes> getRoomTypes() {
    return roomTypes;
  }
  public void setRoomTypes(List<HotelProductRoomTypes> roomTypes) {
    this.roomTypes = roomTypes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<HotelProductRatePlans> getRatePlans() {
    return ratePlans;
  }
  public void setRatePlans(List<HotelProductRatePlans> ratePlans) {
    this.ratePlans = ratePlans;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelProduct hotelProduct = (HotelProduct) o;
    return (this.ID == null ? hotelProduct.ID == null : this.ID.equals(hotelProduct.ID)) &&
        (this.roomTypes == null ? hotelProduct.roomTypes == null : this.roomTypes.equals(hotelProduct.roomTypes)) &&
        (this.ratePlans == null ? hotelProduct.ratePlans == null : this.ratePlans.equals(hotelProduct.ratePlans));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    result = 31 * result + (this.roomTypes == null ? 0: this.roomTypes.hashCode());
    result = 31 * result + (this.ratePlans == null ? 0: this.ratePlans.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelProduct {\n");
    
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("  roomTypes: ").append(roomTypes).append("\n");
    sb.append("  ratePlans: ").append(ratePlans).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
