/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.io.Serializable;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Provides information regarding affiliations, loyalty programs and award ratings.The AffiliationInfo object is used to identify the brand or franchise affiliations of the hotel.
 **/
@ApiModel(description = "Provides information regarding affiliations, loyalty programs and award ratings.The AffiliationInfo object is used to identify the brand or franchise affiliations of the hotel.")
public class HotelDescriptiveInfoAffiliationInfo implements Serializable {
  private static final long serialVersionUID = 112559L;

  @SerializedName("awards")
  private List<Award> awards = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Award> getAwards() {
    return awards;
  }
  public void setAwards(List<Award> awards) {
    this.awards = awards;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelDescriptiveInfoAffiliationInfo hotelDescriptiveInfoAffiliationInfo = (HotelDescriptiveInfoAffiliationInfo) o;
    return (this.awards == null ? hotelDescriptiveInfoAffiliationInfo.awards == null : this.awards.equals(hotelDescriptiveInfoAffiliationInfo.awards));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.awards == null ? 0: this.awards.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelDescriptiveInfoAffiliationInfo {\n");
    
    sb.append("  awards: ").append(awards).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
