/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HotelConfig {
  
  @SerializedName("logoUrl")
  private String logoUrl = null;
  @SerializedName("primaryColor")
  private String primaryColor = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogoUrl() {
    return logoUrl;
  }
  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPrimaryColor() {
    return primaryColor;
  }
  public void setPrimaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelConfig hotelConfig = (HotelConfig) o;
    return (this.logoUrl == null ? hotelConfig.logoUrl == null : this.logoUrl.equals(hotelConfig.logoUrl)) &&
        (this.primaryColor == null ? hotelConfig.primaryColor == null : this.primaryColor.equals(hotelConfig.primaryColor));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.logoUrl == null ? 0: this.logoUrl.hashCode());
    result = 31 * result + (this.primaryColor == null ? 0: this.primaryColor.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelConfig {\n");
    
    sb.append("  logoUrl: ").append(logoUrl).append("\n");
    sb.append("  primaryColor: ").append(primaryColor).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
