/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("status")
  private ReservationStatus status = null;
  @SerializedName("reservationId")
  private String reservationId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ReservationStatus getStatus() {
    return status;
  }
  public void setStatus(ReservationStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReservationId() {
    return reservationId;
  }
  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.status == null ? inlineResponse200.status == null : this.status.equals(inlineResponse200.status)) &&
        (this.reservationId == null ? inlineResponse200.reservationId == null : this.reservationId.equals(inlineResponse200.reservationId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.reservationId == null ? 0: this.reservationId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  reservationId: ").append(reservationId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
