/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

@ApiModel(description = "")
public class MultimediaDescriptionTexts implements Serializable {
  private static final long serialVersionUID = 112579L;

  @SerializedName("detailsCode")
  private Integer detailsCode = null;
  @SerializedName("text")
  private String text = null;

  /**
   * Used to designate a particular type of additional information. [Here is the list of the possible Additional Detail Type (ADT) values](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325600/Additional+Detail+Type+ADT)
   **/
  @ApiModelProperty(value = "Used to designate a particular type of additional information. [Here is the list of the possible Additional Detail Type (ADT) values](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325600/Additional+Detail+Type+ADT)")
  public Integer getDetailsCode() {
    return detailsCode;
  }
  public void setDetailsCode(Integer detailsCode) {
    this.detailsCode = detailsCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getText() {
    return text;
  }
  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultimediaDescriptionTexts multimediaDescriptionTexts = (MultimediaDescriptionTexts) o;
    return (this.detailsCode == null ? multimediaDescriptionTexts.detailsCode == null : this.detailsCode.equals(multimediaDescriptionTexts.detailsCode)) &&
        (this.text == null ? multimediaDescriptionTexts.text == null : this.text.equals(multimediaDescriptionTexts.text));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.detailsCode == null ? 0: this.detailsCode.hashCode());
    result = 31 * result + (this.text == null ? 0: this.text.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultimediaDescriptionTexts {\n");
    
    sb.append("  detailsCode: ").append(detailsCode).append("\n");
    sb.append("  text: ").append(text).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
