/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MultiDescription {
  
  @SerializedName("texts")
  private List<String> texts = null;
  @SerializedName("images")
  private List<String> images = null;
  @SerializedName("urls")
  private List<String> urls = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getTexts() {
    return texts;
  }
  public void setTexts(List<String> texts) {
    this.texts = texts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getImages() {
    return images;
  }
  public void setImages(List<String> images) {
    this.images = images;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getUrls() {
    return urls;
  }
  public void setUrls(List<String> urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiDescription multiDescription = (MultiDescription) o;
    return (this.texts == null ? multiDescription.texts == null : this.texts.equals(multiDescription.texts)) &&
        (this.images == null ? multiDescription.images == null : this.images.equals(multiDescription.images)) &&
        (this.urls == null ? multiDescription.urls == null : this.urls.equals(multiDescription.urls));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.texts == null ? 0: this.texts.hashCode());
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    result = 31 * result + (this.urls == null ? 0: this.urls.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiDescription {\n");
    
    sb.append("  texts: ").append(texts).append("\n");
    sb.append("  images: ").append(images).append("\n");
    sb.append("  urls: ").append(urls).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
