/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

@ApiModel(description = "")
public class MultimediaDescriptionImages implements Serializable {
  private static final long serialVersionUID = 112578L;
  @SerializedName("sort")
  private Integer sort = null;
  @SerializedName("imageId")
  private String imageId = null;
  @SerializedName("imageUrl")
  private String imageUrl = null;
  @SerializedName("imageWidth")
  private Integer imageWidth = null;
  @SerializedName("imageHeight")
  private Integer imageHeight = null;
  public enum DimensionCategoryEnum {
     Original,  Thumbnail,  Mobile,  Desktop,  Wide, 
  };
  @SerializedName("dimensionCategory")
  private DimensionCategoryEnum dimensionCategory = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSort() {
    return sort;
  }
  public void setSort(Integer sort) {
    this.sort = sort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageId() {
    return imageId;
  }
  public void setImageId(String imageId) {
    this.imageId = imageId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getImageWidth() {
    return imageWidth;
  }
  public void setImageWidth(Integer imageWidth) {
    this.imageWidth = imageWidth;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getImageHeight() {
    return imageHeight;
  }
  public void setImageHeight(Integer imageHeight) {
    this.imageHeight = imageHeight;
  }

  /**
   * Used to define the category of the image
   **/
  @ApiModelProperty(value = "Used to define the category of the image")
  public DimensionCategoryEnum getDimensionCategory() {
    return dimensionCategory;
  }
  public void setDimensionCategory(DimensionCategoryEnum dimensionCategory) {
    this.dimensionCategory = dimensionCategory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultimediaDescriptionImages multimediaDescriptionImages = (MultimediaDescriptionImages) o;
    return (this.sort == null ? multimediaDescriptionImages.sort == null : this.sort.equals(multimediaDescriptionImages.sort)) &&
        (this.imageId == null ? multimediaDescriptionImages.imageId == null : this.imageId.equals(multimediaDescriptionImages.imageId)) &&
        (this.imageUrl == null ? multimediaDescriptionImages.imageUrl == null : this.imageUrl.equals(multimediaDescriptionImages.imageUrl)) &&
        (this.imageWidth == null ? multimediaDescriptionImages.imageWidth == null : this.imageWidth.equals(multimediaDescriptionImages.imageWidth)) &&
        (this.imageHeight == null ? multimediaDescriptionImages.imageHeight == null : this.imageHeight.equals(multimediaDescriptionImages.imageHeight)) &&
        (this.dimensionCategory == null ? multimediaDescriptionImages.dimensionCategory == null : this.dimensionCategory.equals(multimediaDescriptionImages.dimensionCategory));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sort == null ? 0: this.sort.hashCode());
    result = 31 * result + (this.imageId == null ? 0: this.imageId.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.imageWidth == null ? 0: this.imageWidth.hashCode());
    result = 31 * result + (this.imageHeight == null ? 0: this.imageHeight.hashCode());
    result = 31 * result + (this.dimensionCategory == null ? 0: this.dimensionCategory.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultimediaDescriptionImages {\n");
    
    sb.append("  sort: ").append(sort).append("\n");
    sb.append("  imageId: ").append(imageId).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  imageWidth: ").append(imageWidth).append("\n");
    sb.append("  imageHeight: ").append(imageHeight).append("\n");
    sb.append("  dimensionCategory: ").append(dimensionCategory).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
