/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MultimediaDescription {
  
  @SerializedName("images")
  private List<MultimediaDescriptionImages> images = null;
  @SerializedName("texts")
  private List<MultimediaDescriptionTexts> texts = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MultimediaDescriptionImages> getImages() {
    return images;
  }
  public void setImages(List<MultimediaDescriptionImages> images) {
    this.images = images;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MultimediaDescriptionTexts> getTexts() {
    return texts;
  }
  public void setTexts(List<MultimediaDescriptionTexts> texts) {
    this.texts = texts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultimediaDescription multimediaDescription = (MultimediaDescription) o;
    return (this.images == null ? multimediaDescription.images == null : this.images.equals(multimediaDescription.images)) &&
        (this.texts == null ? multimediaDescription.texts == null : this.texts.equals(multimediaDescription.texts));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    result = 31 * result + (this.texts == null ? 0: this.texts.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultimediaDescription {\n");
    
    sb.append("  images: ").append(images).append("\n");
    sb.append("  texts: ").append(texts).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
