/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

@ApiModel(description = "")
public class PaymentCard implements Serializable {
  private static final long serialVersionUID = 112580L;

  public enum CardCodeEnum {
     AX,  VI,  MC,  EC,  DN,  JC,  DS,  MA,  BL,  CB,  BC,  CU,  TP, 
  };
  @SerializedName("cardCode")
  private CardCodeEnum cardCode = null;
  @SerializedName("cardNumber")
  private String cardNumber = null;
  @SerializedName("expireDate")
  private String expireDate = null;
  @SerializedName("cardHolderName")
  private String cardHolderName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public CardCodeEnum getCardCode() {
    return cardCode;
  }
  public void setCardCode(CardCodeEnum cardCode) {
    this.cardCode = cardCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }
  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExpireDate() {
    return expireDate;
  }
  public void setExpireDate(String expireDate) {
    this.expireDate = expireDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCardHolderName() {
    return cardHolderName;
  }
  public void setCardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentCard paymentCard = (PaymentCard) o;
    return (this.cardCode == null ? paymentCard.cardCode == null : this.cardCode.equals(paymentCard.cardCode)) &&
        (this.cardNumber == null ? paymentCard.cardNumber == null : this.cardNumber.equals(paymentCard.cardNumber)) &&
        (this.expireDate == null ? paymentCard.expireDate == null : this.expireDate.equals(paymentCard.expireDate)) &&
        (this.cardHolderName == null ? paymentCard.cardHolderName == null : this.cardHolderName.equals(paymentCard.cardHolderName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cardCode == null ? 0: this.cardCode.hashCode());
    result = 31 * result + (this.cardNumber == null ? 0: this.cardNumber.hashCode());
    result = 31 * result + (this.expireDate == null ? 0: this.expireDate.hashCode());
    result = 31 * result + (this.cardHolderName == null ? 0: this.cardHolderName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentCard {\n");
    
    sb.append("  cardCode: ").append(cardCode).append("\n");
    sb.append("  cardNumber: ").append(cardNumber).append("\n");
    sb.append("  expireDate: ").append(expireDate).append("\n");
    sb.append("  cardHolderName: ").append(cardHolderName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
