/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Phone {
  
  @SerializedName("phoneTechType")
  private Integer phoneTechType = null;
  @SerializedName("countryAccessCode")
  private String countryAccessCode = null;
  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPhoneTechType() {
    return phoneTechType;
  }
  public void setPhoneTechType(Integer phoneTechType) {
    this.phoneTechType = phoneTechType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryAccessCode() {
    return countryAccessCode;
  }
  public void setCountryAccessCode(String countryAccessCode) {
    this.countryAccessCode = countryAccessCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phone phone = (Phone) o;
    return (this.phoneTechType == null ? phone.phoneTechType == null : this.phoneTechType.equals(phone.phoneTechType)) &&
        (this.countryAccessCode == null ? phone.countryAccessCode == null : this.countryAccessCode.equals(phone.countryAccessCode)) &&
        (this.phoneNumber == null ? phone.phoneNumber == null : this.phoneNumber.equals(phone.phoneNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.phoneTechType == null ? 0: this.phoneTechType.hashCode());
    result = 31 * result + (this.countryAccessCode == null ? 0: this.countryAccessCode.hashCode());
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phone {\n");
    
    sb.append("  phoneTechType: ").append(phoneTechType).append("\n");
    sb.append("  countryAccessCode: ").append(countryAccessCode).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
