/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReservationRequest {
  
  @SerializedName("sessionId")
  private String sessionId = null;
  @SerializedName("roomStays")
  private List<RoomStay> roomStays = null;
  @SerializedName("guestInfo")
  private Profile guestInfo = null;
  @SerializedName("paymentCard")
  private Object paymentCard = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSessionId() {
    return sessionId;
  }
  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<RoomStay> getRoomStays() {
    return roomStays;
  }
  public void setRoomStays(List<RoomStay> roomStays) {
    this.roomStays = roomStays;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Profile getGuestInfo() {
    return guestInfo;
  }
  public void setGuestInfo(Profile guestInfo) {
    this.guestInfo = guestInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getPaymentCard() {
    return paymentCard;
  }
  public void setPaymentCard(Object paymentCard) {
    this.paymentCard = paymentCard;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationRequest reservationRequest = (ReservationRequest) o;
    return (this.sessionId == null ? reservationRequest.sessionId == null : this.sessionId.equals(reservationRequest.sessionId)) &&
        (this.roomStays == null ? reservationRequest.roomStays == null : this.roomStays.equals(reservationRequest.roomStays)) &&
        (this.guestInfo == null ? reservationRequest.guestInfo == null : this.guestInfo.equals(reservationRequest.guestInfo)) &&
        (this.paymentCard == null ? reservationRequest.paymentCard == null : this.paymentCard.equals(reservationRequest.paymentCard));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sessionId == null ? 0: this.sessionId.hashCode());
    result = 31 * result + (this.roomStays == null ? 0: this.roomStays.hashCode());
    result = 31 * result + (this.guestInfo == null ? 0: this.guestInfo.hashCode());
    result = 31 * result + (this.paymentCard == null ? 0: this.paymentCard.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationRequest {\n");
    
    sb.append("  sessionId: ").append(sessionId).append("\n");
    sb.append("  roomStays: ").append(roomStays).append("\n");
    sb.append("  guestInfo: ").append(guestInfo).append("\n");
    sb.append("  paymentCard: ").append(paymentCard).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
