/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReservationResGlobalInfoGuarantee {
  
  @SerializedName("paymentCard")
  private PaymentCard paymentCard = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public PaymentCard getPaymentCard() {
    return paymentCard;
  }
  public void setPaymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationResGlobalInfoGuarantee reservationResGlobalInfoGuarantee = (ReservationResGlobalInfoGuarantee) o;
    return (this.paymentCard == null ? reservationResGlobalInfoGuarantee.paymentCard == null : this.paymentCard.equals(reservationResGlobalInfoGuarantee.paymentCard));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paymentCard == null ? 0: this.paymentCard.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationResGlobalInfoGuarantee {\n");
    
    sb.append("  paymentCard: ").append(paymentCard).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
