/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReservationResGlobalInfo {
  
  @SerializedName("timeSpan")
  private TimeSpan timeSpan = null;
  @SerializedName("comments")
  private List<String> comments = null;
  @SerializedName("guarantee")
  private ReservationResGlobalInfoGuarantee guarantee = null;
  @SerializedName("total")
  private Total total = null;
  @SerializedName("guestCounts")
  private List<GuestCount> guestCounts = null;
  @SerializedName("profiles")
  private List<Profile> profiles = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public TimeSpan getTimeSpan() {
    return timeSpan;
  }
  public void setTimeSpan(TimeSpan timeSpan) {
    this.timeSpan = timeSpan;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getComments() {
    return comments;
  }
  public void setComments(List<String> comments) {
    this.comments = comments;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ReservationResGlobalInfoGuarantee getGuarantee() {
    return guarantee;
  }
  public void setGuarantee(ReservationResGlobalInfoGuarantee guarantee) {
    this.guarantee = guarantee;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Total getTotal() {
    return total;
  }
  public void setTotal(Total total) {
    this.total = total;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<GuestCount> getGuestCounts() {
    return guestCounts;
  }
  public void setGuestCounts(List<GuestCount> guestCounts) {
    this.guestCounts = guestCounts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Profile> getProfiles() {
    return profiles;
  }
  public void setProfiles(List<Profile> profiles) {
    this.profiles = profiles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationResGlobalInfo reservationResGlobalInfo = (ReservationResGlobalInfo) o;
    return (this.timeSpan == null ? reservationResGlobalInfo.timeSpan == null : this.timeSpan.equals(reservationResGlobalInfo.timeSpan)) &&
        (this.comments == null ? reservationResGlobalInfo.comments == null : this.comments.equals(reservationResGlobalInfo.comments)) &&
        (this.guarantee == null ? reservationResGlobalInfo.guarantee == null : this.guarantee.equals(reservationResGlobalInfo.guarantee)) &&
        (this.total == null ? reservationResGlobalInfo.total == null : this.total.equals(reservationResGlobalInfo.total)) &&
        (this.guestCounts == null ? reservationResGlobalInfo.guestCounts == null : this.guestCounts.equals(reservationResGlobalInfo.guestCounts)) &&
        (this.profiles == null ? reservationResGlobalInfo.profiles == null : this.profiles.equals(reservationResGlobalInfo.profiles));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.timeSpan == null ? 0: this.timeSpan.hashCode());
    result = 31 * result + (this.comments == null ? 0: this.comments.hashCode());
    result = 31 * result + (this.guarantee == null ? 0: this.guarantee.hashCode());
    result = 31 * result + (this.total == null ? 0: this.total.hashCode());
    result = 31 * result + (this.guestCounts == null ? 0: this.guestCounts.hashCode());
    result = 31 * result + (this.profiles == null ? 0: this.profiles.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationResGlobalInfo {\n");
    
    sb.append("  timeSpan: ").append(timeSpan).append("\n");
    sb.append("  comments: ").append(comments).append("\n");
    sb.append("  guarantee: ").append(guarantee).append("\n");
    sb.append("  total: ").append(total).append("\n");
    sb.append("  guestCounts: ").append(guestCounts).append("\n");
    sb.append("  profiles: ").append(profiles).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
