/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Reservation {
  
  @SerializedName("hotelReservationId")
  private String hotelReservationId = null;
  @SerializedName("status")
  private ReservationStatus status = null;
  @SerializedName("createDateTime")
  private String createDateTime = null;
  @SerializedName("lastModifyDateTime")
  private String lastModifyDateTime = null;
  @SerializedName("roomStays")
  private List<ReservationRoomStay> roomStays = null;
  @SerializedName("resGuests")
  private List<ReservationResGuest> resGuests = null;
  @SerializedName("resGlobalInfo")
  private ReservationResGlobalInfo resGlobalInfo = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHotelReservationId() {
    return hotelReservationId;
  }
  public void setHotelReservationId(String hotelReservationId) {
    this.hotelReservationId = hotelReservationId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ReservationStatus getStatus() {
    return status;
  }
  public void setStatus(ReservationStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreateDateTime() {
    return createDateTime;
  }
  public void setCreateDateTime(String createDateTime) {
    this.createDateTime = createDateTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastModifyDateTime() {
    return lastModifyDateTime;
  }
  public void setLastModifyDateTime(String lastModifyDateTime) {
    this.lastModifyDateTime = lastModifyDateTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ReservationRoomStay> getRoomStays() {
    return roomStays;
  }
  public void setRoomStays(List<ReservationRoomStay> roomStays) {
    this.roomStays = roomStays;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ReservationResGuest> getResGuests() {
    return resGuests;
  }
  public void setResGuests(List<ReservationResGuest> resGuests) {
    this.resGuests = resGuests;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ReservationResGlobalInfo getResGlobalInfo() {
    return resGlobalInfo;
  }
  public void setResGlobalInfo(ReservationResGlobalInfo resGlobalInfo) {
    this.resGlobalInfo = resGlobalInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reservation reservation = (Reservation) o;
    return (this.hotelReservationId == null ? reservation.hotelReservationId == null : this.hotelReservationId.equals(reservation.hotelReservationId)) &&
        (this.status == null ? reservation.status == null : this.status.equals(reservation.status)) &&
        (this.createDateTime == null ? reservation.createDateTime == null : this.createDateTime.equals(reservation.createDateTime)) &&
        (this.lastModifyDateTime == null ? reservation.lastModifyDateTime == null : this.lastModifyDateTime.equals(reservation.lastModifyDateTime)) &&
        (this.roomStays == null ? reservation.roomStays == null : this.roomStays.equals(reservation.roomStays)) &&
        (this.resGuests == null ? reservation.resGuests == null : this.resGuests.equals(reservation.resGuests)) &&
        (this.resGlobalInfo == null ? reservation.resGlobalInfo == null : this.resGlobalInfo.equals(reservation.resGlobalInfo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.hotelReservationId == null ? 0: this.hotelReservationId.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.createDateTime == null ? 0: this.createDateTime.hashCode());
    result = 31 * result + (this.lastModifyDateTime == null ? 0: this.lastModifyDateTime.hashCode());
    result = 31 * result + (this.roomStays == null ? 0: this.roomStays.hashCode());
    result = 31 * result + (this.resGuests == null ? 0: this.resGuests.hashCode());
    result = 31 * result + (this.resGlobalInfo == null ? 0: this.resGlobalInfo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reservation {\n");
    
    sb.append("  hotelReservationId: ").append(hotelReservationId).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  createDateTime: ").append(createDateTime).append("\n");
    sb.append("  lastModifyDateTime: ").append(lastModifyDateTime).append("\n");
    sb.append("  roomStays: ").append(roomStays).append("\n");
    sb.append("  resGuests: ").append(resGuests).append("\n");
    sb.append("  resGlobalInfo: ").append(resGlobalInfo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
