/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReservationRoomStay {
  
  @SerializedName("status")
  private ReservationStatus status = null;
  @SerializedName("roomId")
  private String roomId = null;
  @SerializedName("ratePlanId")
  private String ratePlanId = null;
  @SerializedName("rates")
  private List<RoomRate> rates = null;
  @SerializedName("guestCounts")
  private List<GuestCount> guestCounts = null;
  @SerializedName("timeSpan")
  private TimeSpan timeSpan = null;
  @SerializedName("total")
  private Total total = null;
  @SerializedName("cancelPenalties")
  private CancelPenalties cancelPenalties = null;
  @SerializedName("resGuestRphs")
  private List<Integer> resGuestRphs = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ReservationStatus getStatus() {
    return status;
  }
  public void setStatus(ReservationStatus status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRoomId() {
    return roomId;
  }
  public void setRoomId(String roomId) {
    this.roomId = roomId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRatePlanId() {
    return ratePlanId;
  }
  public void setRatePlanId(String ratePlanId) {
    this.ratePlanId = ratePlanId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<RoomRate> getRates() {
    return rates;
  }
  public void setRates(List<RoomRate> rates) {
    this.rates = rates;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<GuestCount> getGuestCounts() {
    return guestCounts;
  }
  public void setGuestCounts(List<GuestCount> guestCounts) {
    this.guestCounts = guestCounts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TimeSpan getTimeSpan() {
    return timeSpan;
  }
  public void setTimeSpan(TimeSpan timeSpan) {
    this.timeSpan = timeSpan;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Total getTotal() {
    return total;
  }
  public void setTotal(Total total) {
    this.total = total;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CancelPenalties getCancelPenalties() {
    return cancelPenalties;
  }
  public void setCancelPenalties(CancelPenalties cancelPenalties) {
    this.cancelPenalties = cancelPenalties;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getResGuestRphs() {
    return resGuestRphs;
  }
  public void setResGuestRphs(List<Integer> resGuestRphs) {
    this.resGuestRphs = resGuestRphs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationRoomStay reservationRoomStay = (ReservationRoomStay) o;
    return (this.status == null ? reservationRoomStay.status == null : this.status.equals(reservationRoomStay.status)) &&
        (this.roomId == null ? reservationRoomStay.roomId == null : this.roomId.equals(reservationRoomStay.roomId)) &&
        (this.ratePlanId == null ? reservationRoomStay.ratePlanId == null : this.ratePlanId.equals(reservationRoomStay.ratePlanId)) &&
        (this.rates == null ? reservationRoomStay.rates == null : this.rates.equals(reservationRoomStay.rates)) &&
        (this.guestCounts == null ? reservationRoomStay.guestCounts == null : this.guestCounts.equals(reservationRoomStay.guestCounts)) &&
        (this.timeSpan == null ? reservationRoomStay.timeSpan == null : this.timeSpan.equals(reservationRoomStay.timeSpan)) &&
        (this.total == null ? reservationRoomStay.total == null : this.total.equals(reservationRoomStay.total)) &&
        (this.cancelPenalties == null ? reservationRoomStay.cancelPenalties == null : this.cancelPenalties.equals(reservationRoomStay.cancelPenalties)) &&
        (this.resGuestRphs == null ? reservationRoomStay.resGuestRphs == null : this.resGuestRphs.equals(reservationRoomStay.resGuestRphs));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.roomId == null ? 0: this.roomId.hashCode());
    result = 31 * result + (this.ratePlanId == null ? 0: this.ratePlanId.hashCode());
    result = 31 * result + (this.rates == null ? 0: this.rates.hashCode());
    result = 31 * result + (this.guestCounts == null ? 0: this.guestCounts.hashCode());
    result = 31 * result + (this.timeSpan == null ? 0: this.timeSpan.hashCode());
    result = 31 * result + (this.total == null ? 0: this.total.hashCode());
    result = 31 * result + (this.cancelPenalties == null ? 0: this.cancelPenalties.hashCode());
    result = 31 * result + (this.resGuestRphs == null ? 0: this.resGuestRphs.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationRoomStay {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  roomId: ").append(roomId).append("\n");
    sb.append("  ratePlanId: ").append(ratePlanId).append("\n");
    sb.append("  rates: ").append(rates).append("\n");
    sb.append("  guestCounts: ").append(guestCounts).append("\n");
    sb.append("  timeSpan: ").append(timeSpan).append("\n");
    sb.append("  total: ").append(total).append("\n");
    sb.append("  cancelPenalties: ").append(cancelPenalties).append("\n");
    sb.append("  resGuestRphs: ").append(resGuestRphs).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
