/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RoomAvailabilityResult {
  
  @SerializedName("guestroomId")
  private String guestroomId = null;
  @SerializedName("products")
  private List<AvailabilityResult> products = null;

  /**
   * ID of the room type
   **/
  @ApiModelProperty(value = "ID of the room type")
  public String getGuestroomId() {
    return guestroomId;
  }
  public void setGuestroomId(String guestroomId) {
    this.guestroomId = guestroomId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AvailabilityResult> getProducts() {
    return products;
  }
  public void setProducts(List<AvailabilityResult> products) {
    this.products = products;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomAvailabilityResult roomAvailabilityResult = (RoomAvailabilityResult) o;
    return (this.guestroomId == null ? roomAvailabilityResult.guestroomId == null : this.guestroomId.equals(roomAvailabilityResult.guestroomId)) &&
        (this.products == null ? roomAvailabilityResult.products == null : this.products.equals(roomAvailabilityResult.products));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.guestroomId == null ? 0: this.guestroomId.hashCode());
    result = 31 * result + (this.products == null ? 0: this.products.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomAvailabilityResult {\n");
    
    sb.append("  guestroomId: ").append(guestroomId).append("\n");
    sb.append("  products: ").append(products).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
