/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RoomStay {
  
  @SerializedName("guestRoomId")
  private String guestRoomId = null;
  @SerializedName("rateplanId")
  private String rateplanId = null;
  @SerializedName("startDate")
  private Date startDate = null;
  @SerializedName("endDate")
  private Date endDate = null;
  @SerializedName("nbAdults")
  private Integer nbAdults = null;
  @SerializedName("nbChildren")
  private Integer nbChildren = null;
  @SerializedName("nbInfants")
  private Integer nbInfants = null;
  @SerializedName("totalPrice")
  private Float totalPrice = null;
  @SerializedName("totalDiscount")
  private Float totalDiscount = null;
  @SerializedName("services")
  private List<BasicService> services = null;

  /**
   * ID of the selected room type
   **/
  @ApiModelProperty(value = "ID of the selected room type")
  public String getGuestRoomId() {
    return guestRoomId;
  }
  public void setGuestRoomId(String guestRoomId) {
    this.guestRoomId = guestRoomId;
  }

  /**
   * ID of the selected rate plan
   **/
  @ApiModelProperty(value = "ID of the selected rate plan")
  public String getRateplanId() {
    return rateplanId;
  }
  public void setRateplanId(String rateplanId) {
    this.rateplanId = rateplanId;
  }

  /**
   * Start date of the stay (date of arrival)
   **/
  @ApiModelProperty(value = "Start date of the stay (date of arrival)")
  public Date getStartDate() {
    return startDate;
  }
  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  /**
   * End date of the stay (date of departure)
   **/
  @ApiModelProperty(value = "End date of the stay (date of departure)")
  public Date getEndDate() {
    return endDate;
  }
  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  /**
   * Number of adults for the stay
   **/
  @ApiModelProperty(value = "Number of adults for the stay")
  public Integer getNbAdults() {
    return nbAdults;
  }
  public void setNbAdults(Integer nbAdults) {
    this.nbAdults = nbAdults;
  }

  /**
   * Number of children for the stay
   **/
  @ApiModelProperty(value = "Number of children for the stay")
  public Integer getNbChildren() {
    return nbChildren;
  }
  public void setNbChildren(Integer nbChildren) {
    this.nbChildren = nbChildren;
  }

  /**
   * Number of infants for the stay
   **/
  @ApiModelProperty(value = "Number of infants for the stay")
  public Integer getNbInfants() {
    return nbInfants;
  }
  public void setNbInfants(Integer nbInfants) {
    this.nbInfants = nbInfants;
  }

  /**
   * Total price for the stay
   **/
  @ApiModelProperty(value = "Total price for the stay")
  public Float getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Total of the discounts on the stay
   **/
  @ApiModelProperty(value = "Total of the discounts on the stay")
  public Float getTotalDiscount() {
    return totalDiscount;
  }
  public void setTotalDiscount(Float totalDiscount) {
    this.totalDiscount = totalDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BasicService> getServices() {
    return services;
  }
  public void setServices(List<BasicService> services) {
    this.services = services;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomStay roomStay = (RoomStay) o;
    return (this.guestRoomId == null ? roomStay.guestRoomId == null : this.guestRoomId.equals(roomStay.guestRoomId)) &&
        (this.rateplanId == null ? roomStay.rateplanId == null : this.rateplanId.equals(roomStay.rateplanId)) &&
        (this.startDate == null ? roomStay.startDate == null : this.startDate.equals(roomStay.startDate)) &&
        (this.endDate == null ? roomStay.endDate == null : this.endDate.equals(roomStay.endDate)) &&
        (this.nbAdults == null ? roomStay.nbAdults == null : this.nbAdults.equals(roomStay.nbAdults)) &&
        (this.nbChildren == null ? roomStay.nbChildren == null : this.nbChildren.equals(roomStay.nbChildren)) &&
        (this.nbInfants == null ? roomStay.nbInfants == null : this.nbInfants.equals(roomStay.nbInfants)) &&
        (this.totalPrice == null ? roomStay.totalPrice == null : this.totalPrice.equals(roomStay.totalPrice)) &&
        (this.totalDiscount == null ? roomStay.totalDiscount == null : this.totalDiscount.equals(roomStay.totalDiscount)) &&
        (this.services == null ? roomStay.services == null : this.services.equals(roomStay.services));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.guestRoomId == null ? 0: this.guestRoomId.hashCode());
    result = 31 * result + (this.rateplanId == null ? 0: this.rateplanId.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.endDate == null ? 0: this.endDate.hashCode());
    result = 31 * result + (this.nbAdults == null ? 0: this.nbAdults.hashCode());
    result = 31 * result + (this.nbChildren == null ? 0: this.nbChildren.hashCode());
    result = 31 * result + (this.nbInfants == null ? 0: this.nbInfants.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.totalDiscount == null ? 0: this.totalDiscount.hashCode());
    result = 31 * result + (this.services == null ? 0: this.services.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomStay {\n");
    
    sb.append("  guestRoomId: ").append(guestRoomId).append("\n");
    sb.append("  rateplanId: ").append(rateplanId).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  endDate: ").append(endDate).append("\n");
    sb.append("  nbAdults: ").append(nbAdults).append("\n");
    sb.append("  nbChildren: ").append(nbChildren).append("\n");
    sb.append("  nbInfants: ").append(nbInfants).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  totalDiscount: ").append(totalDiscount).append("\n");
    sb.append("  services: ").append(services).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
