/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Tangible room item(s) (e.g., newspaper) available to the guest.
 **/
@ApiModel(description = "Tangible room item(s) (e.g., newspaper) available to the guest.")
public class RoomAmenity implements Serializable {
  private static final long serialVersionUID = 112584L;

  @SerializedName("roomAmenityCode")
  private Integer roomAmenityCode = null;
  @SerializedName("codeDetail")
  private String codeDetail = null;

  /**
   * Refer to OpenTravel Code List Room Amenity Type (RMA).
   **/
  @ApiModelProperty(value = "Refer to OpenTravel Code List Room Amenity Type (RMA).")
  public Integer getRoomAmenityCode() {
    return roomAmenityCode;
  }
  public void setRoomAmenityCode(Integer roomAmenityCode) {
    this.roomAmenityCode = roomAmenityCode;
  }

  /**
   * May be used to give further detail on the code.
   **/
  @ApiModelProperty(value = "May be used to give further detail on the code.")
  public String getCodeDetail() {
    return codeDetail;
  }
  public void setCodeDetail(String codeDetail) {
    this.codeDetail = codeDetail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomAmenity roomAmenity = (RoomAmenity) o;
    return (this.roomAmenityCode == null ? roomAmenity.roomAmenityCode == null : this.roomAmenityCode.equals(roomAmenity.roomAmenityCode)) &&
        (this.codeDetail == null ? roomAmenity.codeDetail == null : this.codeDetail.equals(roomAmenity.codeDetail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.roomAmenityCode == null ? 0: this.roomAmenityCode.hashCode());
    result = 31 * result + (this.codeDetail == null ? 0: this.codeDetail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomAmenity {\n");
    
    sb.append("  roomAmenityCode: ").append(roomAmenityCode).append("\n");
    sb.append("  codeDetail: ").append(codeDetail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
