/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import java.io.Serializable;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RoomRate implements Serializable {
  private static final long serialVersionUID = 112588L;

  @SerializedName("date")
  private Date date = null;
  @SerializedName("amountAfterTax")
  private Float amountAfterTax = null;
  @SerializedName("currencyCode")
  private CurrencyCode currencyCode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDate() {
    return date;
  }
  public void setDate(Date date) {
    this.date = date;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getAmountAfterTax() {
    return amountAfterTax;
  }
  public void setAmountAfterTax(Float amountAfterTax) {
    this.amountAfterTax = amountAfterTax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CurrencyCode getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(CurrencyCode currencyCode) {
    this.currencyCode = currencyCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomRate roomRate = (RoomRate) o;
    return (this.date == null ? roomRate.date == null : this.date.equals(roomRate.date)) &&
        (this.amountAfterTax == null ? roomRate.amountAfterTax == null : this.amountAfterTax.equals(roomRate.amountAfterTax)) &&
        (this.currencyCode == null ? roomRate.currencyCode == null : this.currencyCode.equals(roomRate.currencyCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.date == null ? 0: this.date.hashCode());
    result = 31 * result + (this.amountAfterTax == null ? 0: this.amountAfterTax.hashCode());
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomRate {\n");
    
    sb.append("  date: ").append(date).append("\n");
    sb.append("  amountAfterTax: ").append(amountAfterTax).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
