/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Service {
  
  @SerializedName("code")
  private String code = null;
  @SerializedName("codeDetails")
  private String codeDetails = null;

  /**
   * The code for a service or amenity. Refer to OpenTravel Code List Hotel Amenity Code (HAC).
   **/
  @ApiModelProperty(value = "The code for a service or amenity. Refer to OpenTravel Code List Hotel Amenity Code (HAC).")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }

  /**
   * May be used to give further detail on the code. (Information about which list the code refers to)
   **/
  @ApiModelProperty(value = "May be used to give further detail on the code. (Information about which list the code refers to)")
  public String getCodeDetails() {
    return codeDetails;
  }
  public void setCodeDetails(String codeDetails) {
    this.codeDetails = codeDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return (this.code == null ? service.code == null : this.code.equals(service.code)) &&
        (this.codeDetails == null ? service.codeDetails == null : this.codeDetails.equals(service.codeDetails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.codeDetails == null ? 0: this.codeDetails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("  code: ").append(code).append("\n");
    sb.append("  codeDetails: ").append(codeDetails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
