/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceResultItem extends BasicService {
  
  @SerializedName("serviceId")
  private String serviceId = null;
  @SerializedName("price")
  private Float price = null;
  @SerializedName("discount")
  private Float discount = null;

  @SerializedName("pricingType")
  private PricingTypeEnum pricingType = null;
  @SerializedName("totalPrice")
  private Float totalPrice = null;
  @SerializedName("totalDiscount")
  private Float totalDiscount = null;
  @SerializedName("currency")
  private CurrencyCode currency = null;
  @SerializedName("included")
  private Boolean included = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("proximityCode")
  private Integer proximityCode = null;
  @SerializedName("descriptions")
  private MultiDescription descriptions = null;

  /**
   * ID of the service
   **/
  @ApiModelProperty(value = "ID of the service")
  public String getServiceId() {
    return serviceId;
  }
  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  /**
   * Price of the service
   **/
  @ApiModelProperty(value = "Price of the service")
  public Float getPrice() {
    return price;
  }
  public void setPrice(Float price) {
    this.price = price;
  }

  /**
   * Discount amount offered on this service
   **/
  @ApiModelProperty(value = "Discount amount offered on this service")
  public Float getDiscount() {
    return discount;
  }
  public void setDiscount(Float discount) {
    this.discount = discount;
  }

  /**
   * The pricing type of the service
   **/
  @ApiModelProperty(value = "The pricing type of the service")
  public PricingTypeEnum getPricingType() {
    return pricingType;
  }
  public void setPricingType(PricingTypeEnum pricingType) {
    this.pricingType = pricingType;
  }

  /**
   * Total price for the service
   **/
  @ApiModelProperty(value = "Total price for the service")
  public Float getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Total discount amount offered on this service
   **/
  @ApiModelProperty(value = "Total discount amount offered on this service")
  public Float getTotalDiscount() {
    return totalDiscount;
  }
  public void setTotalDiscount(Float totalDiscount) {
    this.totalDiscount = totalDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CurrencyCode getCurrency() {
    return currency;
  }
  public void setCurrency(CurrencyCode currency) {
    this.currency = currency;
  }

  /**
   * Whether the service price is included in the roomstay price or not
   **/
  @ApiModelProperty(value = "Whether the service price is included in the roomstay price or not")
  public Boolean getIncluded() {
    return included;
  }
  public void setIncluded(Boolean included) {
    this.included = included;
  }

  /**
   * Name of the service
   **/
  @ApiModelProperty(value = "Name of the service")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Indication about whether a service is onsite or offsite. [Here is the list of the possible Proximity Code (PRX) values](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325559/Proximity+PRX)
   **/
  @ApiModelProperty(value = "Indication about whether a service is onsite or offsite. [Here is the list of the possible Proximity Code (PRX) values](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325559/Proximity+PRX)")
  public Integer getProximityCode() {
    return proximityCode;
  }
  public void setProximityCode(Integer proximityCode) {
    this.proximityCode = proximityCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MultiDescription getDescriptions() {
    return descriptions;
  }
  public void setDescriptions(MultiDescription descriptions) {
    this.descriptions = descriptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceResultItem serviceResultItem = (ServiceResultItem) o;
    return (this.serviceId == null ? serviceResultItem.serviceId == null : this.serviceId.equals(serviceResultItem.serviceId)) &&
        (this.price == null ? serviceResultItem.price == null : this.price.equals(serviceResultItem.price)) &&
        (this.discount == null ? serviceResultItem.discount == null : this.discount.equals(serviceResultItem.discount)) &&
        (this.pricingType == null ? serviceResultItem.pricingType == null : this.pricingType.equals(serviceResultItem.pricingType)) &&
        (this.totalPrice == null ? serviceResultItem.totalPrice == null : this.totalPrice.equals(serviceResultItem.totalPrice)) &&
        (this.totalDiscount == null ? serviceResultItem.totalDiscount == null : this.totalDiscount.equals(serviceResultItem.totalDiscount)) &&
        (this.currency == null ? serviceResultItem.currency == null : this.currency.equals(serviceResultItem.currency)) &&
        (this.included == null ? serviceResultItem.included == null : this.included.equals(serviceResultItem.included)) &&
        (this.name == null ? serviceResultItem.name == null : this.name.equals(serviceResultItem.name)) &&
        (this.proximityCode == null ? serviceResultItem.proximityCode == null : this.proximityCode.equals(serviceResultItem.proximityCode)) &&
        (this.descriptions == null ? serviceResultItem.descriptions == null : this.descriptions.equals(serviceResultItem.descriptions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.serviceId == null ? 0: this.serviceId.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.discount == null ? 0: this.discount.hashCode());
    result = 31 * result + (this.pricingType == null ? 0: this.pricingType.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.totalDiscount == null ? 0: this.totalDiscount.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.included == null ? 0: this.included.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.proximityCode == null ? 0: this.proximityCode.hashCode());
    result = 31 * result + (this.descriptions == null ? 0: this.descriptions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceResultItem {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  serviceId: ").append(serviceId).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  discount: ").append(discount).append("\n");
    sb.append("  pricingType: ").append(pricingType).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  totalDiscount: ").append(totalDiscount).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  included: ").append(included).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  proximityCode: ").append(proximityCode).append("\n");
    sb.append("  descriptions: ").append(descriptions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
