/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TypeRoom {
  
  @SerializedName("standardOccupancy")
  private Integer standardOccupancy = null;
  @SerializedName("standardNumBeds")
  private Integer standardNumBeds = null;
  @SerializedName("maxCribs")
  private Integer maxCribs = null;
  @SerializedName("maxRollaways")
  private Integer maxRollaways = null;
  @SerializedName("composite")
  private Boolean composite = null;
  @SerializedName("quantity")
  private Integer quantity = null;

  /**
   * Indicates the usual number of guests that occupy this room.
   **/
  @ApiModelProperty(value = "Indicates the usual number of guests that occupy this room.")
  public Integer getStandardOccupancy() {
    return standardOccupancy;
  }
  public void setStandardOccupancy(Integer standardOccupancy) {
    this.standardOccupancy = standardOccupancy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStandardNumBeds() {
    return standardNumBeds;
  }
  public void setStandardNumBeds(Integer standardNumBeds) {
    this.standardNumBeds = standardNumBeds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxCribs() {
    return maxCribs;
  }
  public void setMaxCribs(Integer maxCribs) {
    this.maxCribs = maxCribs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxRollaways() {
    return maxRollaways;
  }
  public void setMaxRollaways(Integer maxRollaways) {
    this.maxRollaways = maxRollaways;
  }

  /**
   * Indicates that the room (suite) is a composite of smaller units.
   **/
  @ApiModelProperty(value = "Indicates that the room (suite) is a composite of smaller units.")
  public Boolean getComposite() {
    return composite;
  }
  public void setComposite(Boolean composite) {
    this.composite = composite;
  }

  /**
   * Defines the number of the item in question. Used for Numeric values, from 1 to 9999 inclusive.
   **/
  @ApiModelProperty(value = "Defines the number of the item in question. Used for Numeric values, from 1 to 9999 inclusive.")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeRoom typeRoom = (TypeRoom) o;
    return (this.standardOccupancy == null ? typeRoom.standardOccupancy == null : this.standardOccupancy.equals(typeRoom.standardOccupancy)) &&
        (this.standardNumBeds == null ? typeRoom.standardNumBeds == null : this.standardNumBeds.equals(typeRoom.standardNumBeds)) &&
        (this.maxCribs == null ? typeRoom.maxCribs == null : this.maxCribs.equals(typeRoom.maxCribs)) &&
        (this.maxRollaways == null ? typeRoom.maxRollaways == null : this.maxRollaways.equals(typeRoom.maxRollaways)) &&
        (this.composite == null ? typeRoom.composite == null : this.composite.equals(typeRoom.composite)) &&
        (this.quantity == null ? typeRoom.quantity == null : this.quantity.equals(typeRoom.quantity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.standardOccupancy == null ? 0: this.standardOccupancy.hashCode());
    result = 31 * result + (this.standardNumBeds == null ? 0: this.standardNumBeds.hashCode());
    result = 31 * result + (this.maxCribs == null ? 0: this.maxCribs.hashCode());
    result = 31 * result + (this.maxRollaways == null ? 0: this.maxRollaways.hashCode());
    result = 31 * result + (this.composite == null ? 0: this.composite.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeRoom {\n");
    
    sb.append("  standardOccupancy: ").append(standardOccupancy).append("\n");
    sb.append("  standardNumBeds: ").append(standardNumBeds).append("\n");
    sb.append("  maxCribs: ").append(maxCribs).append("\n");
    sb.append("  maxRollaways: ").append(maxRollaways).append("\n");
    sb.append("  composite: ").append(composite).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
