/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger statusCode generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.server;

public class APIError extends Exception {
  int statusCode = 0;
  String message = null;

  public APIError() {}

  public APIError(int code, String message) {
    this.statusCode = code;
    this.message = message;
  }

  /**
   * Get the HTTP status statusCode.
   *
   * @return HTTP status statusCode
   */
  public int getStatusCode() {
    return statusCode;
  }

  /**
   * Set the HTTP status statusCode.
   *
   * @param statusCode HTTP status statusCode.
   */
  public void setStatusCode(int statusCode) {
    this.statusCode = statusCode;
  }

  /**
   * Get the error message.
   *
   * @return Error message.
   */
  public String getMessage() {
    return message;
  }

  /**
   * Set the error messages.
   *
   * @param message Error message.
   */
  public void setMessage(String message) {
    this.message = message;
  }
}
