/**
 * Hotel-Spider CRS API
 * Here is the documentation of the Hotel-Spider CRS API version 2. An API key is mandatory for each call described below.
 *
 * OpenAPI spec version: 2.0
 * Contact: dev@hotel-spider.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.fhnw.bedwaste.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import ch.fhnw.bedwaste.model.*;


public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Address".equalsIgnoreCase(className)) {
      return new TypeToken<List<Address>>(){}.getType();
    }
    
    if ("AvailabilityResult".equalsIgnoreCase(className)) {
      return new TypeToken<List<AvailabilityResult>>(){}.getType();
    }
    
    if ("AvailabilityResults".equalsIgnoreCase(className)) {
      return new TypeToken<List<AvailabilityResults>>(){}.getType();
    }
    
    if ("Award".equalsIgnoreCase(className)) {
      return new TypeToken<List<Award>>(){}.getType();
    }
    
    if ("BasicService".equalsIgnoreCase(className)) {
      return new TypeToken<List<BasicService>>(){}.getType();
    }
    
    if ("CalendarResults".equalsIgnoreCase(className)) {
      return new TypeToken<List<CalendarResults>>(){}.getType();
    }
    
    if ("CancelPenalties".equalsIgnoreCase(className)) {
      return new TypeToken<List<CancelPenalties>>(){}.getType();
    }
    
    if ("CancelReservationRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<CancelReservationRequest>>(){}.getType();
    }
    
    if ("ContactInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<ContactInfo>>(){}.getType();
    }
    
    if ("CurrencyCode".equalsIgnoreCase(className)) {
      return new TypeToken<List<CurrencyCode>>(){}.getType();
    }
    
    if ("Descriptions".equalsIgnoreCase(className)) {
      return new TypeToken<List<Descriptions>>(){}.getType();
    }
    
    if ("Email".equalsIgnoreCase(className)) {
      return new TypeToken<List<Email>>(){}.getType();
    }
    
    if ("GuestCount".equalsIgnoreCase(className)) {
      return new TypeToken<List<GuestCount>>(){}.getType();
    }
    
    if ("GuestRoom".equalsIgnoreCase(className)) {
      return new TypeToken<List<GuestRoom>>(){}.getType();
    }
    
    if ("HotelConfig".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelConfig>>(){}.getType();
    }
    
    if ("HotelDescriptiveInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelDescriptiveInfo>>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoAffiliationInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelDescriptiveInfoAffiliationInfo>>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoFacilityInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelDescriptiveInfoFacilityInfo>>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoPolicies".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelDescriptiveInfoPolicies>>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoPoliciesPolicyInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelDescriptiveInfoPoliciesPolicyInfo>>(){}.getType();
    }
    
    if ("HotelInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelInfo>>(){}.getType();
    }
    
    if ("HotelInfoPosition".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelInfoPosition>>(){}.getType();
    }
    
    if ("HotelProduct".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelProduct>>(){}.getType();
    }
    
    if ("HotelProductRatePlans".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelProductRatePlans>>(){}.getType();
    }
    
    if ("HotelProductRoomTypes".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelProductRoomTypes>>(){}.getType();
    }
    
    if ("HotelProducts".equalsIgnoreCase(className)) {
      return new TypeToken<List<HotelProducts>>(){}.getType();
    }
    
    if ("InlineResponse200".equalsIgnoreCase(className)) {
      return new TypeToken<List<InlineResponse200>>(){}.getType();
    }
    
    if ("MultiDescription".equalsIgnoreCase(className)) {
      return new TypeToken<List<MultiDescription>>(){}.getType();
    }
    
    if ("MultimediaDescription".equalsIgnoreCase(className)) {
      return new TypeToken<List<MultimediaDescription>>(){}.getType();
    }
    
    if ("MultimediaDescriptionImages".equalsIgnoreCase(className)) {
      return new TypeToken<List<MultimediaDescriptionImages>>(){}.getType();
    }
    
    if ("MultimediaDescriptionTexts".equalsIgnoreCase(className)) {
      return new TypeToken<List<MultimediaDescriptionTexts>>(){}.getType();
    }
    
    if ("PaymentCard".equalsIgnoreCase(className)) {
      return new TypeToken<List<PaymentCard>>(){}.getType();
    }
    
    if ("Phone".equalsIgnoreCase(className)) {
      return new TypeToken<List<Phone>>(){}.getType();
    }
    
    if ("Profile".equalsIgnoreCase(className)) {
      return new TypeToken<List<Profile>>(){}.getType();
    }
    
    if ("Reservation".equalsIgnoreCase(className)) {
      return new TypeToken<List<Reservation>>(){}.getType();
    }
    
    if ("ReservationRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationRequest>>(){}.getType();
    }
    
    if ("ReservationResGlobalInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationResGlobalInfo>>(){}.getType();
    }
    
    if ("ReservationResGlobalInfoGuarantee".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationResGlobalInfoGuarantee>>(){}.getType();
    }
    
    if ("ReservationResGuest".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationResGuest>>(){}.getType();
    }
    
    if ("ReservationRoomStay".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationRoomStay>>(){}.getType();
    }
    
    if ("ReservationStatus".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReservationStatus>>(){}.getType();
    }
    
    if ("RoomAmenity".equalsIgnoreCase(className)) {
      return new TypeToken<List<RoomAmenity>>(){}.getType();
    }
    
    if ("RoomAvailabilityResult".equalsIgnoreCase(className)) {
      return new TypeToken<List<RoomAvailabilityResult>>(){}.getType();
    }
    
    if ("RoomRate".equalsIgnoreCase(className)) {
      return new TypeToken<List<RoomRate>>(){}.getType();
    }
    
    if ("RoomStay".equalsIgnoreCase(className)) {
      return new TypeToken<List<RoomStay>>(){}.getType();
    }
    
    if ("Service".equalsIgnoreCase(className)) {
      return new TypeToken<List<Service>>(){}.getType();
    }
    
    if ("ServiceResultItem".equalsIgnoreCase(className)) {
      return new TypeToken<List<ServiceResultItem>>(){}.getType();
    }
    
    if ("ServiceResults".equalsIgnoreCase(className)) {
      return new TypeToken<List<ServiceResults>>(){}.getType();
    }
    
    if ("TimeSpan".equalsIgnoreCase(className)) {
      return new TypeToken<List<TimeSpan>>(){}.getType();
    }
    
    if ("Total".equalsIgnoreCase(className)) {
      return new TypeToken<List<Total>>(){}.getType();
    }
    
    if ("TypeRoom".equalsIgnoreCase(className)) {
      return new TypeToken<List<TypeRoom>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Address".equalsIgnoreCase(className)) {
      return new TypeToken<Address>(){}.getType();
    }
    
    if ("AvailabilityResult".equalsIgnoreCase(className)) {
      return new TypeToken<AvailabilityResult>(){}.getType();
    }
    
    if ("AvailabilityResults".equalsIgnoreCase(className)) {
      return new TypeToken<AvailabilityResults>(){}.getType();
    }
    
    if ("Award".equalsIgnoreCase(className)) {
      return new TypeToken<Award>(){}.getType();
    }
    
    if ("BasicService".equalsIgnoreCase(className)) {
      return new TypeToken<BasicService>(){}.getType();
    }
    
    if ("CalendarResults".equalsIgnoreCase(className)) {
      return new TypeToken<CalendarResults>(){}.getType();
    }
    
    if ("CancelPenalties".equalsIgnoreCase(className)) {
      return new TypeToken<CancelPenalties>(){}.getType();
    }
    
    if ("CancelReservationRequest".equalsIgnoreCase(className)) {
      return new TypeToken<CancelReservationRequest>(){}.getType();
    }
    
    if ("ContactInfo".equalsIgnoreCase(className)) {
      return new TypeToken<ContactInfo>(){}.getType();
    }
    
    if ("CurrencyCode".equalsIgnoreCase(className)) {
      return new TypeToken<CurrencyCode>(){}.getType();
    }
    
    if ("Descriptions".equalsIgnoreCase(className)) {
      return new TypeToken<Descriptions>(){}.getType();
    }
    
    if ("Email".equalsIgnoreCase(className)) {
      return new TypeToken<Email>(){}.getType();
    }
    
    if ("GuestCount".equalsIgnoreCase(className)) {
      return new TypeToken<GuestCount>(){}.getType();
    }
    
    if ("GuestRoom".equalsIgnoreCase(className)) {
      return new TypeToken<GuestRoom>(){}.getType();
    }
    
    if ("HotelConfig".equalsIgnoreCase(className)) {
      return new TypeToken<HotelConfig>(){}.getType();
    }
    
    if ("HotelDescriptiveInfo".equalsIgnoreCase(className)) {
      return new TypeToken<HotelDescriptiveInfo>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoAffiliationInfo".equalsIgnoreCase(className)) {
      return new TypeToken<HotelDescriptiveInfoAffiliationInfo>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoFacilityInfo".equalsIgnoreCase(className)) {
      return new TypeToken<HotelDescriptiveInfoFacilityInfo>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoPolicies".equalsIgnoreCase(className)) {
      return new TypeToken<HotelDescriptiveInfoPolicies>(){}.getType();
    }
    
    if ("HotelDescriptiveInfoPoliciesPolicyInfo".equalsIgnoreCase(className)) {
      return new TypeToken<HotelDescriptiveInfoPoliciesPolicyInfo>(){}.getType();
    }
    
    if ("HotelInfo".equalsIgnoreCase(className)) {
      return new TypeToken<HotelInfo>(){}.getType();
    }
    
    if ("HotelInfoPosition".equalsIgnoreCase(className)) {
      return new TypeToken<HotelInfoPosition>(){}.getType();
    }
    
    if ("HotelProduct".equalsIgnoreCase(className)) {
      return new TypeToken<HotelProduct>(){}.getType();
    }
    
    if ("HotelProductRatePlans".equalsIgnoreCase(className)) {
      return new TypeToken<HotelProductRatePlans>(){}.getType();
    }
    
    if ("HotelProductRoomTypes".equalsIgnoreCase(className)) {
      return new TypeToken<HotelProductRoomTypes>(){}.getType();
    }
    
    if ("HotelProducts".equalsIgnoreCase(className)) {
      return new TypeToken<HotelProducts>(){}.getType();
    }
    
    if ("InlineResponse200".equalsIgnoreCase(className)) {
      return new TypeToken<InlineResponse200>(){}.getType();
    }
    
    if ("MultiDescription".equalsIgnoreCase(className)) {
      return new TypeToken<MultiDescription>(){}.getType();
    }
    
    if ("MultimediaDescription".equalsIgnoreCase(className)) {
      return new TypeToken<MultimediaDescription>(){}.getType();
    }
    
    if ("MultimediaDescriptionImages".equalsIgnoreCase(className)) {
      return new TypeToken<MultimediaDescriptionImages>(){}.getType();
    }
    
    if ("MultimediaDescriptionTexts".equalsIgnoreCase(className)) {
      return new TypeToken<MultimediaDescriptionTexts>(){}.getType();
    }
    
    if ("PaymentCard".equalsIgnoreCase(className)) {
      return new TypeToken<PaymentCard>(){}.getType();
    }
    
    if ("Phone".equalsIgnoreCase(className)) {
      return new TypeToken<Phone>(){}.getType();
    }
    
    if ("Profile".equalsIgnoreCase(className)) {
      return new TypeToken<Profile>(){}.getType();
    }
    
    if ("Reservation".equalsIgnoreCase(className)) {
      return new TypeToken<Reservation>(){}.getType();
    }
    
    if ("ReservationRequest".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationRequest>(){}.getType();
    }
    
    if ("ReservationResGlobalInfo".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationResGlobalInfo>(){}.getType();
    }
    
    if ("ReservationResGlobalInfoGuarantee".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationResGlobalInfoGuarantee>(){}.getType();
    }
    
    if ("ReservationResGuest".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationResGuest>(){}.getType();
    }
    
    if ("ReservationRoomStay".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationRoomStay>(){}.getType();
    }
    
    if ("ReservationStatus".equalsIgnoreCase(className)) {
      return new TypeToken<ReservationStatus>(){}.getType();
    }
    
    if ("RoomAmenity".equalsIgnoreCase(className)) {
      return new TypeToken<RoomAmenity>(){}.getType();
    }
    
    if ("RoomAvailabilityResult".equalsIgnoreCase(className)) {
      return new TypeToken<RoomAvailabilityResult>(){}.getType();
    }
    
    if ("RoomRate".equalsIgnoreCase(className)) {
      return new TypeToken<RoomRate>(){}.getType();
    }
    
    if ("RoomStay".equalsIgnoreCase(className)) {
      return new TypeToken<RoomStay>(){}.getType();
    }
    
    if ("Service".equalsIgnoreCase(className)) {
      return new TypeToken<Service>(){}.getType();
    }
    
    if ("ServiceResultItem".equalsIgnoreCase(className)) {
      return new TypeToken<ServiceResultItem>(){}.getType();
    }
    
    if ("ServiceResults".equalsIgnoreCase(className)) {
      return new TypeToken<ServiceResults>(){}.getType();
    }
    
    if ("TimeSpan".equalsIgnoreCase(className)) {
      return new TypeToken<TimeSpan>(){}.getType();
    }
    
    if ("Total".equalsIgnoreCase(className)) {
      return new TypeToken<Total>(){}.getType();
    }
    
    if ("TypeRoom".equalsIgnoreCase(className)) {
      return new TypeToken<TypeRoom>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
